CREATE TABLE ojos(
  "id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL,
  "roll" FLOAT NOT NULL, 
  "yaw" FLOAT NOT NULL, 
  "pitch" FLOAT NOT NULL,
  "p19x" INTEGER NOT NULL , "p19y" INTEGER NOT NULL,
  "p20x" INTEGER NOT NULL , "p20y" INTEGER NOT NULL,
  "p21x" INTEGER NOT NULL , "p21y" INTEGER NOT NULL,
  "p22x" INTEGER NOT NULL , "p22y" INTEGER NOT NULL,
  "p23x" INTEGER NOT NULL , "p23y" INTEGER NOT NULL,
  "p24x" INTEGER NOT NULL , "p24y" INTEGER NOT NULL,
  "p25x" INTEGER NOT NULL , "p25y" INTEGER NOT NULL,
  "p26x" INTEGER NOT NULL , "p26y" INTEGER NOT NULL,
  "p27x" INTEGER NOT NULL , "p27y" INTEGER NOT NULL,
  "p28x" INTEGER NOT NULL , "p28y" INTEGER NOT NULL,
  "p29x" INTEGER NOT NULL , "p29y" INTEGER NOT NULL,
  "p30x" INTEGER NOT NULL , "p30y" INTEGER NOT NULL,
  "state" INTEGER NOT NULL
  );