drop table sct1;
CREATE TABLE sct1(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct2;
CREATE TABLE sct2(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct3;
CREATE TABLE sct3(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct4;
CREATE TABLE sct4(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct5;
CREATE TABLE sct5(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct6;
CREATE TABLE sct6(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct7;
CREATE TABLE sct7(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct8;
CREATE TABLE sct8(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );
drop table sct9;
CREATE TABLE IF NOT EXISTS sct9(
  id int(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  roll float NOT NULL, 
  yaw float NOT NULL, 
  pitch float NOT NULL,
  x19 int(4) NOT NULL ,
  y19 int(4) NOT NULL,
  x20 int(4) NOT NULL , 
  y20 int(4) NOT NULL,
  x21 int(4) NOT NULL , 
  y21 int(4) NOT NULL,
  x22 int(4) NOT NULL , 
  y22 int(4) NOT NULL,
  x23 int(4) NOT NULL , 
  y23 int(4) NOT NULL,
  x24 int(4) NOT NULL , 
  y24 int(4) NOT NULL,
  x25 int(4) NOT NULL , 
  y25 int(4) NOT NULL,
  x26 int(4) NOT NULL , 
  y26 int(4) NOT NULL,
  x27 int(4) NOT NULL , 
  y27 int(4) NOT NULL,
  x28 int(4) NOT NULL ,
  y28 int(4) NOT NULL,
  x29 int(4) NOT NULL , 
  y29 int(4) NOT NULL,
  x30 int(4) NOT NULL , 
  y30 int(4) NOT NULL,
  cx int(3) NOT NULL,
  cy int(3) NOT NULL
  );